on:
  pull_request:
    branches:
      - master

name: build

jobs:
  build:
    name: Build
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      id: build
      env:
        DOCKER_TAG: magicxor/radstudio:xe8upd1-delphi-net3.5-ltsc2019
      run: |
        $currentDir = (Get-Location).Path;
        docker run -v "${currentDir}:C:\build\app" ${env:DOCKER_TAG} powershell -Command 'msbuild /t:build /p:Config=Release /p:Platform=Win64 C:\build\app\ClipboardTransform\ClipboardTransform.dproj; Set-Content -NoNewline -Force -Path C:\build\app\build_result_64.txt -Value $LastExitCode; msbuild /t:build /p:Config=Release /p:Platform=Win32 C:\build\app\ClipboardTransform\ClipboardTransform.dproj; Set-Content -NoNewline -Force -Path C:\build\app\build_result_32.txt -Value $LastExitCode;';
        $buildResult64 = Get-Content -Path build_result_64.txt;
        $buildResult32 = Get-Content -Path build_result_32.txt;
        if ($buildResult64 -ne '0') { throw ('msbuild exit code: ' + $buildResult64); } else { Write-Host ('msbuild exit code: ' + $buildResult64); }
        if ($buildResult32 -ne '0') { throw ('msbuild exit code: ' + $buildResult32); } else { Write-Host ('msbuild exit code: ' + $buildResult32); }
